name: timetable

services:
    database:
        container_name: timetable-database
        restart: unless-stopped
        image: postgres:17
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
            - /tmp:/backups
        networks:
            - default

    server:
        container_name: timetable-server
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:3000
        depends_on:
            - database
        networks:
            - default

volumes:
    postgres_data:

networks:
    default:
