version: "3.8"

services:
    database:
        image: postgres:16
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres

    server:
        build:
            context: .
        ports:
            - 80:3000
        depends_on:
            - database
